### PR TITLE
Feature 22

### PR DESCRIPTION
**Pull request by staskie**
Hi @Ghostbird and @luisfontes19,

This is my attempt to implement this feature. Graph below:

opened_vs_closed

Let me know what you think and if it works for you.

Thanks

### CODE REVIEW

**Comment by Ghostbird** [comment]
This seems good, but I don't understand it fully since there seem to be no explanation of how the trend is defined. Since the colour green suggests that a high value is better, but I think that originally I asked for Open tickets / min(0,Closed tickets), where a high value is worse. An Y-axis label to clear this up would make the graph useful.

**Comment by staskie** [comment]
Okay, after those improvements the graph looks like this:

screen shot 2015-08-25 at 18 32 14

Regarding the calculations of trend, for the given data the algorithm is:

Opened issues for 3 months [1, 4, 5]
Closed issues for 3 months  [0, 2, 4]

Cumulative opened issues: [1, 5, 10]
Cumulative closed issues:   [0, 2, 6]

The result will be:

[1, 2.5, 1.667]

**Comment by Ghostbird** [comment]
This looks great!

**Comment by peternijssen** [comment]
Nice graph. Would be nice to see it getting merged :)

**Pull request closed without merging**
